services:
  bookrentalsystem:
    image: ${DOCKER_REGISTRY-}bookrentalsystem
    container_name: bookrentalsystemapi
    build:
      context: .
      dockerfile: BookRentalSystem/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  bookrentalsystem-db:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: bookrentalsystemdb
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - bookrentalsystem-data:/var/opt/mssql

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    container_name: bookrentalsystemfrontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - bookrentalsystem-data:/var/opt/mssql

volumes:
  bookrentalsystem-data:
