services:
  bookrentalsystem:
    image: bookrentalsystemapi
    container_name: bookrentalsystemapi
    build:
      context: .
      dockerfile: BookRentalSystem/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - bookrentalsystem-db
    networks:
      - backend-network

  bookrentalsystem-db:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: bookrentalsystemdb
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - bookrentalsystem-data:/var/opt/mssql
    networks:
      - backend-network

volumes:
  bookrentalsystem-data:

networks:
  backend-network:    