@BookRentalSystem_HostAddress = http://localhost:5075


POST {{BookRentalSystem_HostAddress}}/api/v1/category/
Accept: application/json
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Category 1 Description"
}

###

GET {{BookRentalSystem_HostAddress}}/api/v1/category/1
Accept: application/json

###

DELETE {{BookRentalSystem_HostAddress}}/api/v1/category/1
Accept: application/json

###

PUT {{BookRentalSystem_HostAddress}}/api/v1/category/1
Accept: application/json
Content-Type: application/json

{
    "name": "Updated Category",
    "description": "Updated Description"
}

###
